### ISSUE TITLE
Attribute error with emulator_linpk is preventing import pyccl.

### ISSUE THREAD

**Issue by bruno-moraes** [LSSTDESC/CCL#1123]
Hi,

I have a joint developer CCL + firecrown installation on my MacBook Pro (Intel). I just pulled from the master branch to get from version 2.8.1 to the most recent version. Imports and examples were working fine before. Now, I get the following error:

`(descstack) brunomor@Brunos-MacBook-Pro ~ % python -c "import pyccl as ccl;print(ccl.__version__);print(ccl.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/brunomor/lib/python/CCL/pyccl/__init__.py", line 46, in <module>
    from .cosmology import *
  File "/Users/brunomor/lib/python/CCL/pyccl/cosmology.py", line 64, in <module>
    'emulator': lib.emulator_linpk
                ^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyccl.ccllib' has no attribute 'emulator_linpk'`

Any suggestions?

Thanks!

**Comment by damonge** [comment]
Most likely explanation is that there is some lingering old version of the library which hasn't been purged. I'd uninstall, ensure there's no remnant of CCL, and then reinstall with v3
