### ISSUE TITLE
Trispectrum computation for connected non-Gaussian 3x2pt covariance

### ISSUE THREAD

**Issue by davidesciotti** [LSSTDESC/CCL#1145]
Hi, 
I am trying to compute the cNG covariance for 3x2pt; for the trispectrum, I use the method  `ccl.halos.pk_4pt.halomod_Tk3D_cNG` (which is referenced in the [CCL v3 documentation](https://ccl.readthedocs.io/en/latest/api/pyccl.halos.pk_4pt.html#pyccl.halos.pk_4pt.halomod_Tk3D_cNG) but does not seem to be in the actual v3.0 release; I cloned the master branch instead), but when computing the galaxy-galaxy lensing (in this example, this is the trispectrum I'll use for the GLGL covariance block, G=galaxy, L=lensing) I get the error:

```python
Computing trispectrum for cNG, probe combination LLLL
Computing trispectrum for cNG, probe combination LLGL
Computing trispectrum for cNG, probe combination LLGG
Computing trispectrum for cNG, probe combination GLGL
Traceback (most recent call last):
  File "/export/NAS/cosmo/data/davide.sciotti/Spaceborne/jobs/SPV3_magcut_zcut_thesis/bin/main_SPV3_magcut_zcut_thesis.py", line 858, in <module>
    cov_dict = covmat_utils.compute_cov(general_cfg, covariance_cfg,
  File "/home/cosmo/davide.sciotti/data/Spaceborne/bin/covariance.py", line 372, in compute_cov
    cov_ng_ccl_3x2pt_10D_dict = get_cov_ng_pyccl(general_cfg, covariance_cfg, which_ng_cov, ell_dict)
  File "/home/cosmo/davide.sciotti/data/Spaceborne/bin/covariance.py", line 176, in get_cov_ng_pyccl
    cov_ccl_3x2pt_dict_8D = pyccl_cov.compute_cov_ng_with_pyccl(general_cfg['fid_pars_dict'], probe,
  File "/home/cosmo/davide.sciotti/data/Spaceborne/bin/pyccl_cov.py", line 412, in compute_cov_ng_with_pyccl
    tkka_dict = initialize_trispectrum(cosmo_ccl, which_ng_cov, probe_ordering, pyccl_cfg, p_of_k_a=None,
  File "/home/cosmo/davide.sciotti/data/Spaceborne/bin/pyccl_cov.py", line 119, in initialize_trispectrum
    tkka_dict[A, B, C, D] = tkka_func(cosmo=cosmo_ccl,
  File "/home/cosmo/davide.sciotti/software/anaconda3/envs/spaceborne/lib/python3.10/site-packages/pyccl/halos/pk_4pt.py", line 1558, in halomod_Tk3D_cNG
    tkk += _halomod_trispectrum_2h_22(cosmo, hmc, np.exp(lk_arr), a_arr,
  File "/home/cosmo/davide.sciotti/software/anaconda3/envs/spaceborne/lib/python3.10/site-packages/pyccl/halos/pk_4pt.py", line 745, in _halomod_trispectrum_2h_22
    i32 = hmc.I_1_2(cosmo, k_use, aa, prof3, prof2=prof2,
  File "/home/cosmo/davide.sciotti/software/anaconda3/envs/spaceborne/lib/python3.10/site-packages/pyccl/halos/halo_model.py", line 375, in I_1_2
    uk = prof_2pt.fourier_2pt(cosmo, k, self._mass, a, prof,
  File "/home/cosmo/davide.sciotti/software/anaconda3/envs/spaceborne/lib/python3.10/site-packages/pyccl/halos/profiles_2pt.py", line 149, in fourier_2pt
    raise ValueError("prof and prof2 must be equivalent")
ValueError: prof and prof2 must be equivalent
```

Note that this does *not* seem to be an issue for the `LLGL` term, for which `prof3 != prof4`. This is the code I'm using:

```python

  halo_profile_dict = {
      'L': halo_profile_nfw,
      'G': halo_profile_hod,
  }
  prof_2pt_dict = {
      ('L', 'L'): ccl.halos.Profile2pt(),
      ('G', 'L'): ccl.halos.Profile2pt(),
      ('L', 'G'): ccl.halos.Profile2pt(),
      ('G', 'G'): ccl.halos.Profile2ptHOD(),
  }

  # store the trispectrum for the various probes in a dictionary
  tkka_dict = {}

  for row, (A, B) in tqdm(enumerate(probe_ordering)):
      for col, (C, D) in enumerate(probe_ordering):
          if col >= row:
              print(f'Computing trispectrum for {which_ng_cov}, probe combination {A}{B}{C}{D}')

              if which_ng_cov == 'SSC':
                  tkka_func = ccl.halos.pk_4pt.halomod_Tk3D_SSC
                  prof_2pt_args = {}
              elif which_ng_cov == 'cNG':
                  tkka_func = ccl.halos.pk_4pt.halomod_Tk3D_cNG
                  prof_2pt_args = {
                      'prof13_2pt': prof_2pt_dict[A, C],
                      'prof14_2pt': prof_2pt_dict[A, D],
                      'prof24_2pt': prof_2pt_dict[B, D]
                  }
              else:
                  raise ValueError(f"Invalid value for which_ng_cov. It is {which_ng_cov}, must be 'SSC' or 'cNG'.")

              tkka_dict[A, B, C, D] = tkka_func(cosmo=cosmo_ccl,
                                                hmc=hmc,
                                                prof=halo_profile_dict[A],
                                                prof2=halo_profile_dict[B],
                                                prof3=halo_profile_dict[C],
                                                prof4=halo_profile_dict[D],
                                                prof12_2pt=prof_2pt_dict[A, B],
                                                prof34_2pt=prof_2pt_dict[C, D],
                                                p_of_k_a=None, lk_arr=k_arr_tkka,
                                                a_arr=a_arr_tkka,
                                                extrap_order_lok=1, extrap_order_hik=1, use_log=False,
                                                **prof_2pt_args)


```

Am I missing something? 
Also, the computation of this term is extremely slow (and I need 6 trispectra for all the independent probe combinations); do you have any idea on the minimum acceptable number of points for the `a` and `k` grids? 

Thanks a lot!

**Comment by davidesciotti** [comment]
I (very partially) answer myself, in case anyone might need this: the trispectrum computation time for 100 redshift values and 512 k values is about 5 hours. The GLGL issue is still present, though.

**Comment by damonge** [comment]
@davidesciotti I'm not able to reproduce this issue. This is my code:
```
import pyccl as ccl
import numpy as np


cosmo = ccl.CosmologyVanillaLCDM()
mdef = ccl.halos.MassDef200c
nM = ccl.halos.MassFuncBocquet16(mass_def=mdef)
bM = ccl.halos.HaloBiasTinker10(mass_def=mdef)
cM = ccl.halos.ConcentrationDuffy08(mass_def=mdef)
hmc = ccl.halos.HMCalculator(mass_function=nM, halo_bias=bM, mass_def=mdef,
                             log10M_max=15., log10M_min=10, nM=32)
pM = ccl.halos.HaloProfileNFW(mass_def=mdef, concentration=cM)
pG = ccl.halos.HaloProfileHOD(mass_def=mdef, concentration=cM)
pMM = ccl.halos.Profile2pt()
pGM = ccl.halos.Profile2pt()
pGG = ccl.halos.Profile2ptHOD()

# Not too many ks to make it fast just for this test
k_arr = np.geomspace(1e-4, 100, 16)
lk_arr = np.log(k_arr)
a_arr = np.linspace(0.3, 1, 8)

p1, p2, p3, p4 = pG, pM, pG, pM
ccl.halos.pk_4pt.halomod_Tk3D_cNG(cosmo=cosmo, hmc=hmc,
                                  prof=p1, prof2=p2, prof3=p3, prof4=p4,
                                  prof12_2pt=pGM, prof13_2pt=pGG, prof14_2pt=pGM,
                                  prof32_2pt=pGM, prof24_2pt=pMM,
                                  lk_arr=lk_arr, a_arr=a_arr)
```

Can you check if you still see this problem?

**Comment by davidesciotti** [comment]
Hi @damonge, thanks for the reply.
Sorry if I didn't report immediately, @carlosggarcia helped me solve the issue some days ago: in my code, I probably mixed the arguments for `halomod_Tk3D_cNG` and I passed an insufficient number of profXX_2pt arguments. Here's the corrected version, which runs smoothly for the 3x2pt case:

```

          elif which_ng_cov == 'cNG':
              tkka_func = ccl.halos.pk_4pt.halomod_Tk3D_cNG
              additional_args = {
                  'prof12_2pt': prof_2pt_dict[A, B],
                  'prof13_2pt': prof_2pt_dict[A, C],
                  'prof14_2pt': prof_2pt_dict[A, D],
                  'prof24_2pt': prof_2pt_dict[B, D],
                  'prof32_2pt': prof_2pt_dict[C, B],
                  'prof34_2pt': prof_2pt_dict[C, D],
                  'p_of_k_a': None,  # TODO pass object? anyway, None takes the pk stored in cosmo
              }
```

Thanks for the support and sorry for the false alarm!
