### ISSUE TITLE
CCL v3.0.0 (in desc-python) MassDef bug?

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/CCL#1162]
I tried to run CCL v3.0.0 (in the desc-python kernel) and got the following error:
Here's the code:
```
>>> import pyccl as ccl
>>> print(ccl.__version__)
3.0.0
>>> hmd_fof = ccl.halos.MassDef
>>> mf = ccl.halos.MassFuncSheth99(mass_def=hmd_fof) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/common/software/lsst/gitlab/desc-python-prod/2024-02-20-26-53/py/lib/python3.10/site-packages/pyccl/halos/hmfunc/sheth99.py", line 33, in __init__
    super().__init__(mass_def=mass_def, mass_def_strict=mass_def_strict)
  File "/global/common/software/lsst/gitlab/desc-python-prod/2024-02-20-26-53/py/lib/python3.10/site-packages/pyccl/halos/halo_model_base.py", line 56, in __init__
    mass_def = MassDef.create_instance(mass_def)
  File "/global/common/software/lsst/gitlab/desc-python-prod/2024-02-20-26-53/py/lib/python3.10/site-packages/pyccl/halos/massdef.py", line 249, in create_instance
    return cls.from_name(input_)
  File "/global/common/software/lsst/gitlab/desc-python-prod/2024-02-20-26-53/py/lib/python3.10/site-packages/pyccl/halos/massdef.py", line 233, in from_name
    MassDefName = f"MassDef{name.capitalize()}"
AttributeError: type object 'MassDef' has no attribute 'capitalize'
>>> 
```
Am I doing something wrong, or is this a bug?

Background information:
I am trying to update some of the DC2 tutorials, and we need to compute the halo mass function.

**Comment by zdu863** [comment]
Looking at the [documentation](https://ccl.readthedocs.io/en/latest/api/pyccl.halos.massdef.html#pyccl.halos.massdef.MassDef) of `MassDef`, I think you need to provide parameters `Delta` and `rho_type`.
For example, `hmd_fof = ccl.halos.MassDef('fof', 'matter')` should work.

**Comment by evevkovacs** [comment]
Thanks, that seems to work.
