### ISSUE TITLE
Pip install is failing

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CCL#449]
pip install pyccl appears to be failing on a remote system that I work on. The error is reproduced below

```  
  cc1plus: error: unrecognized command line option "-std=c++11"
  make[6]: *** [CMakeFiles/libangpow.dir/src/walltimer.cc.o] Error 1
  make[6]: Leaving directory `/tmp/pip-build-TPPuXo/pyccl/build/ANGPOW/src/ANGPOW-build'
  make[5]: *** [CMakeFiles/libangpow.dir/all] Error 2
  make[5]: Leaving directory `/tmp/pip-build-TPPuXo/pyccl/build/ANGPOW/src/ANGPOW-build'
  make[4]: *** [all] Error 2
  make[4]: Leaving directory `/tmp/pip-build-TPPuXo/pyccl/build/ANGPOW/src/ANGPOW-build'
  make[3]: *** [ANGPOW/src/ANGPOW-stamp/ANGPOW-build] Error 2
  make[3]: Leaving directory `/tmp/pip-build-TPPuXo/pyccl/build'
  make[2]: *** [CMakeFiles/ANGPOW.dir/all] Error 2
  make[2]: Leaving directory `/tmp/pip-build-TPPuXo/pyccl/build'
  make[1]: *** [pyccl/CMakeFiles/_ccllib.dir/rule] Error 2
  make[1]: Leaving directory `/tmp/pip-build-TPPuXo/pyccl/build'
  make: *** [_ccllib] Error 2
  make: Leaving directory `/tmp/pip-build-TPPuXo/pyccl/build'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-TPPuXo/pyccl/setup.py", line 65, in <module>
      'Topic :: Scientific/Engineering :: Physics'
    File "/home/matthewkirby/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/home/matthewkirby/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/home/matthewkirby/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/matthewkirby/anaconda2/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/home/matthewkirby/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/matthewkirby/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/matthewkirby/anaconda2/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/home/matthewkirby/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/matthewkirby/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-TPPuXo/pyccl/setup.py", line 17, in run
      raise Exception("Could not build CCL")
  Exception: Could not build CCL
```

I have gone through issues and the readme and I don't see anything that could help me. Any guidance would be appreciated.

**Comment by philbull** [comment]
@matthewkirby What version of `g++` does that system have installed?

**Comment by matthewkirby** [comment]
g++ version is
`gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC) `

**Comment by EiffL** [comment]
hum.... I would say it's because g++ is too old, not sure what's the best way to go about this... can you load a different gcc ? with a `module load` command ?

**Comment by matthewkirby** [comment]
Unfortunately no. I am going to install a local version and we can find out.

**Comment by matthewkirby** [comment]
On second thought, I will talk to the sysadmin and see if he can get it installed. It looks like the system is missing dependencies to install it from source. If I start trying to install things I am going to end up taking more time setting it up than I will save.

**Comment by EiffL** [comment]
Ok, great, also, if it turns out to be too complicated, we can probably come up with a fix to support that version of gcc

**Comment by beckermr** [comment]
Closing this @matthewkirby. Feel free to reopen it if you are still having trouble!
