### ISSUE TITLE
C Install and Python Install Don't Get Along

### ISSUE THREAD

**Issue by villarrealas** [LSSTDESC/CCL#485]
In recent bug-testing I've been trying to have both the C install (generated with cmake combined with `make` + `sudo make install`) and a Conda Python install (generated from a `python setup.py install --user` up and running at the same time. During the installation of Python though, the following error pops up.

```ld: can't write output file: libccl.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libccl.dylib] Error 1
make[2]: *** [CMakeFiles/ccl.dir/all] Error 2
make[1]: *** [pyccl/CMakeFiles/_ccllib.dir/rule] Error 2
make: *** [_ccllib] Error 2
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    'Topic :: Scientific/Engineering :: Physics'
  File "/Users/avillarreal/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/Users/avillarreal/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/avillarreal/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/avillarreal/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/avillarreal/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/avillarreal/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users/avillarreal/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/avillarreal/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/avillarreal/anaconda3/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Users/avillarreal/anaconda3/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/Users/avillarreal/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/avillarreal/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/avillarreal/anaconda3/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/Users/avillarreal/anaconda3/lib/python3.6/distutils/command/install_lib.py", line 105, in build
    self.run_command('build_py')
  File "/Users/avillarreal/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/avillarreal/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 17, in run
    raise Exception("Could not build CCL")
Exception: Could not build CCL
```

This error **not** occur in the case that only pyccl is installed or only the C is compiled. Not sure what causes this, but I would guess it is some sort of permissions error. Adding a sudo to the python install fixes this, but as this seems to be new behavior, I'm bringing it up just to make certain it is intended behavior.

**Comment by villarrealas** [comment]
It's a little hard to say. I did a little further playing around to make sure things still worked fine. I think the result was due to an unnecessary `sudo` in the make install for my MacOS X set-up. It looks like the Python installer attempts to build C shared library libccl.dylib in the same location, but if the python installer isn't run at the same permissions as the C installer, there can be a conflict.

I wonder if this exists in the pip install version; if this is just in the development installation I am happy to throw a warning up and call it a day. If this conflicts with the pip install, that is a bit more problematic.

**Comment by beckermr** [comment]
Wait is `sudo` hard coded? That is bad form and we should fix immediately.

**Comment by villarrealas** [comment]
I don't think `sudo` is hard coded. Typical procedure for building the C library is `make` followed by `make install`. Previous builds have required me to use `sudo make install` due to permissions. This would then interfere with the new python installer (even if I try to build with --user) unless I include a sudo.

Now I seem to need to drop the sudo from make install and it all goes fine.

**Comment by beckermr** [comment]
What is the known issue then? Sounds like this is an old thing the cmake build has solved?

**Comment by villarrealas** [comment]
Specifically that if you need to use a `sudo make install` to set up the C side, you need to use a `sudo python setup.py install` for the Python side.

**Comment by beckermr** [comment]
ahhhh. I don't this qualifies as a CCL install issue, but we can add it to the docs! 

unix/linux permissions are an issue no matter what you are doing. :P

**Comment by villarrealas** [comment]
Indeed. I agree. I'm going to add this to the wiki and close this.

**Comment by rainwoodman** [comment]
pyccl shall probably build the c lib in a standard setuptools directory
rather than the recommended cmake directory.

**Comment by beckermr** [comment]
Ugh. This is hard. Do we really want to force people to install the C lib when doing python?

**Comment by rainwoodman** [comment]
I thought the final python so file links to an archive library. That
archive has to be built. currently it shares the same location as the
building location of the C builder. It is not hard to split them. I will
file a PR.
