### ISSUE TITLE
ccl integration error while running emcee

### ISSUE THREAD

**Issue by humnaawan** [LSSTDESC/CCL#745]
i'm running into an integration error while running CCL with `emcee`:

```
Traceback (most recent call last):
  File "run_sampler.py", line 307, in <module>
    sampler.run_mcmc(pos, nsteps_per_chain, progress=True)
  File "/global/homes/a/awan/.local/lib/python3.7/site-packages/emcee/ensemble.py", line 342, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/global/homes/a/awan/.local/lib/python3.7/site-packages/emcee/ensemble.py", line 301, in sample
    state, accepted = move.propose(model, state)
  File "/global/homes/a/awan/.local/lib/python3.7/site-packages/emcee/moves/red_blue.py", line 92, in propose
    new_log_probs, new_blobs = model.compute_log_prob_fn(q)
  File "/global/homes/a/awan/.local/lib/python3.7/site-packages/emcee/ensemble.py", line 385, in compute_log_prob
    (p[i] for i in range(len(p)))))
  File "/global/homes/a/awan/.local/lib/python3.7/site-packages/emcee/ensemble.py", line 495, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "run_sampler.py", line 253, in logprob
    cls = lt.get_prediction(dic)
  File "run_sampler.py", line 112, in get_prediction
    cls = ccl.angular_cl(cosmo=cosmo, cltracer1=tr[tr1], cltracer2=tr[tr2], ell=ls)
  File "/global/common/software/lsst/common/miniconda/py3-4.5.12/envs/stack/lib/python3.7/site-packages/pyccl/cls.py", line 85, in angular_cl
    check(status, cosmo=cosmo_in)
  File "/global/common/software/lsst/common/miniconda/py3-4.5.12/envs/stack/lib/python3.7/site-packages/pyccl/pyutils.py", line 29, in check
    raise CCLError("Error %s: %s" % (error_types[status], msg))
pyccl.errors.CCLError: Error CCL_ERROR_INTEG: ccl_cls.c: ccl_angular_cls_limber(); integration error
```

i have reasonable priors so i'm not sure whats going wrong. i have run successful small chains but i get the above error too often to run longer ones.

here are my priors, just in case im doing something silly (following the set up in the [sample_emcee.py](https://github.com/LSSTDESC/LSSLike/blob/master/test/sample_emcee.py) script in LSS_Like):
```
def logprior(p):
    om, w, b0, b1, b2, b3 = p

    if 0 < om <= 0.5 and  w < -1/3 \
            and 0 <= np.abs(b0) <= 3 and 0 <= np.abs(b1) <= 3 \
            and 0 <= np.abs(b2) <= 3 and 0 <= np.abs(b3) <= 3: # physical priors
        lnp = np.log(1/0.5) + np.log(3) + 2 * np.log(1/3) + 2 * np.log(1/3) + 2 * np.log(1/3) + 2 * np.log(1/3)
    else:
        return -np.inf
     
    return lnp
```

pinging @damonge @elisachisari. note that this is similar to another open issue (#696) but the error i'm getting doesn't appear to be a CLASS error.

**Comment by humnaawan** [comment]
okay this is resolved: i was being dumb and evaluating the likelihood even when the params were out of the range specified by my priors.
