### ISSUE TITLE
Double-free error in some cases when C_ell = 0 in correlation function calculation

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/CCL#794]
Hi all,

During CI for TXPipe I've encountered an error in CCL where a zero C_ell going into `correlation` can lead to a corruption bug / crash.

I haven't quite figured out the precise path that causes, but have managed to put in some more checks that avoid it, in branch https://github.com/LSSTDESC/CCL/tree/double_free_bug .  That might just be evading another issue though.

Here's an example, which crashes for me at least in python 3.7 and pyccl 2.1.0 under ubuntu.
It doesn't happen in 2.0.1 on macos.

I've also put together a docker image in which you can run ths it at `joezuntz/ccl-error-debug`.  Notes on that below this script.

```
import numpy as np
import pyccl
C_ell = np.zeros(248)

theta = np.array([0.01281598, 0.02624485, 0.05326189, 0.10870941, 0.22152326,
       0.45065021, 0.9166528 , 1.86319592, 3.77051377])

method = 'fftlog'
cosmo = pyccl.Cosmology(Omega_c=0.2545, Omega_b=0.0485, h=0.682, n_s=0.971, sigma8=0.801, A_s=None, Omega_k=0.0, Omega_g=None, Neff=3.046, w0=-1.0, wa=0.0, T_CMB=None, bcm_log10Mc=14.079181246047625, bcm_etab=0.5, bcm_ks=55.0, mu_0=0.0, sigma_0=0.0, m_nu=0.0, m_nu_type=None, z_mg=None, df_mg=None, transfer_function='boltzmann_camb', matter_power_spectrum='halofit', baryons_power_spectrum='nobaryons', mass_function='tinker10', halo_concentration='duffy2008', emulator_neutrinos='strict')

ell = np.array([2.00000000e+00, 3.00000000e+00, 4.00000000e+00, 5.00000000e+00,
       6.00000000e+00, 7.00000000e+00, 8.00000000e+00, 9.00000000e+00,
       1.00000000e+01, 1.10000000e+01, 1.20000000e+01, 1.30000000e+01,
       1.40000000e+01, 1.50000000e+01, 1.60000000e+01, 1.70000000e+01,
       1.80000000e+01, 1.90000000e+01, 2.00000000e+01, 2.10000000e+01,
       2.20000000e+01, 2.30000000e+01, 2.40000000e+01, 2.50000000e+01,
       2.60000000e+01, 2.70000000e+01, 2.80000000e+01, 2.90000000e+01,
       3.00000000e+01, 3.10000000e+01, 3.20000000e+01, 3.30000000e+01,
       3.40000000e+01, 3.50000000e+01, 3.60000000e+01, 3.70000000e+01,
       3.80000000e+01, 3.90000000e+01, 4.00000000e+01, 4.10000000e+01,
       4.20000000e+01, 4.30000000e+01, 4.40000000e+01, 4.50000000e+01,
       4.60000000e+01, 4.70000000e+01, 4.80000000e+01, 4.90000000e+01,
       5.00000000e+01, 5.18135414e+01, 5.36928615e+01, 5.56403460e+01,
       5.76584674e+01, 5.97497878e+01, 6.19169621e+01, 6.41627416e+01,
       6.64899774e+01, 6.89016239e+01, 7.14007429e+01, 7.39905069e+01,
       7.66742039e+01, 7.94552408e+01, 8.23371482e+01, 8.53235847e+01,
       8.84183418e+01, 9.16253483e+01, 9.49486755e+01, 9.83925426e+01,
       1.01961322e+02, 1.05659543e+02, 1.09491902e+02, 1.13463264e+02,
       1.17578671e+02, 1.21843347e+02, 1.26262706e+02, 1.30842359e+02,
       1.35588119e+02, 1.40506013e+02, 1.45602282e+02, 1.50883398e+02,
       1.56356063e+02, 1.62027227e+02, 1.67904089e+02, 1.73994109e+02,
       1.80305020e+02, 1.86844832e+02, 1.93621849e+02, 2.00644674e+02,
       2.07922222e+02, 2.15463733e+02, 2.23278781e+02, 2.31377288e+02,
       2.39769534e+02, 2.48466173e+02, 2.57478247e+02, 2.66817196e+02,
       2.76494877e+02, 2.86523575e+02, 2.96916022e+02, 3.07685412e+02,
       3.18845417e+02, 3.30410205e+02, 3.42394456e+02, 3.54813387e+02,
       3.67682762e+02, 3.81018920e+02, 3.94838792e+02, 4.09159922e+02,
       4.24000491e+02, 4.39379340e+02, 4.55315993e+02, 4.71830681e+02,
       4.88944371e+02, 5.06678788e+02, 5.25056447e+02, 5.44100679e+02,
       5.63835661e+02, 5.84286448e+02, 6.05479001e+02, 6.27440226e+02,
       6.50198003e+02, 6.73781223e+02, 6.98219826e+02, 7.23544837e+02,
       7.49788407e+02, 7.76983854e+02, 8.05165702e+02, 8.34369728e+02,
       8.64633010e+02, 8.95993965e+02, 9.28492408e+02, 9.62169597e+02,
       9.97068285e+02, 1.03323278e+03, 1.07070899e+03, 1.10954449e+03,
       1.14978858e+03, 1.19149237e+03, 1.23470878e+03, 1.27949269e+03,
       1.32590095e+03, 1.37399248e+03, 1.42382832e+03, 1.47547176e+03,
       1.52898834e+03, 1.58444601e+03, 1.64191518e+03, 1.70146880e+03,
       1.76318249e+03, 1.82713458e+03, 1.89340626e+03, 1.96208167e+03,
       2.03324800e+03, 2.10699559e+03, 2.18341806e+03, 2.26261245e+03,
       2.34467927e+03, 2.42972273e+03, 2.51785079e+03, 2.60917532e+03,
       2.70381227e+03, 2.80188178e+03, 2.90350835e+03, 3.00882101e+03,
       3.11795344e+03, 3.23104419e+03, 3.34823684e+03, 3.46968016e+03,
       3.59552833e+03, 3.72594112e+03, 3.86108409e+03, 4.00112881e+03,
       4.14625307e+03, 4.29664110e+03, 4.45248383e+03, 4.61397911e+03,
       4.78133195e+03, 4.95475482e+03, 5.13446788e+03, 5.32069928e+03,
       5.51368545e+03, 5.71367139e+03, 5.92091098e+03, 6.13566733e+03,
       6.35821306e+03, 6.58883072e+03, 6.82781306e+03, 7.07546350e+03,
       7.33209642e+03, 7.59803763e+03, 7.87362474e+03, 8.15920763e+03,
       8.45514885e+03, 8.76182410e+03, 9.07962272e+03, 9.40894816e+03,
       9.75021850e+03, 1.01038670e+04, 1.04703426e+04, 1.08501106e+04,
       1.12436531e+04, 1.16514697e+04, 1.20740782e+04, 1.25120150e+04,
       1.29658361e+04, 1.34361178e+04, 1.39234569e+04, 1.44284722e+04,
       1.49518048e+04, 1.54941192e+04, 1.60561037e+04, 1.66384719e+04,
       1.72419630e+04, 1.78673433e+04, 1.85154066e+04, 1.91869758e+04,
       1.98829033e+04, 2.06040727e+04, 2.13513994e+04, 2.21258324e+04,
       2.29283546e+04, 2.37599850e+04, 2.46217794e+04, 2.55148317e+04,
       2.64402758e+04, 2.73992865e+04, 2.83930813e+04, 2.94229219e+04,
       3.04901156e+04, 3.15960174e+04, 3.27420311e+04, 3.39296117e+04,
       3.51602668e+04, 3.64355588e+04, 3.77571067e+04, 3.91265882e+04,
       4.05457419e+04, 4.20163696e+04, 4.35403381e+04, 4.51195822e+04,
       4.67561068e+04, 4.84519895e+04, 5.02093833e+04, 5.20305192e+04,
       5.39177093e+04, 5.58733492e+04, 5.78999219e+04, 6.00000000e+04])

pyccl.correlation(cosmo=cosmo, ell=ell, C_ell=C_ell, theta=theta, corr_type='gg', method='fftlog')
```

Running under gdb in the docker image reveals the following backtrace:
```
#4  0x00007fc4eff61e84 in _int_free (have_lock=0, p=0x1e64de0, av=0x7fc4f02b5c40 <main_arena>) at malloc.c:4281
#5  __GI___libc_free (mem=0x1e64df0) at malloc.c:3124
#6  0x00007fc4c1c24942 in ccl_tracer_corr_fftlog (status=0x7ffffd969ca8, taper_cl_limits=0x0, do_taper_cl=<optimized out>, corr_type=2001, wtheta=0x1e9c7b0, theta=0x1e8ea80, n_theta=9, cls=0x1e90630, 
    ell=0xf8, n_ell=30808624, cosmo=<optimized out>) at /root/CCL/src/ccl_correlation.c:130
#7  ccl_correlation (cosmo=cosmo@entry=0x1c31f90, n_ell=n_ell@entry=248, ell=ell@entry=0x1d61a30, cls=cls@entry=0x1e90630, n_theta=9, theta=theta@entry=0x1e8ea80, wtheta=0x1e9c7b0, corr_type=2001, 
    do_taper_cl=0, taper_cl_limits=0x0, flag_method=1002, status=0x7ffffd969ca8) at /root/CCL/src/ccl_correlation.c:389
#8  0x00007fc4c1c06cd7 in correlation_vec (cosmo=cosmo@entry=0x1c31f90, larr=larr@entry=0x1d61a30, nlarr=nlarr@entry=248, clarr=clarr@entry=0x1e90630, nclarr=nclarr@entry=248, 
    theta=theta@entry=0x1e8ea80, nt=<optimized out>, corr_type=2001, method=<optimized out>, nout=<optimized out>, output=<optimized out>, status=0x7ffffd969ca8)
    at /root/CCL/build/pyccl/cclPYTHON_wrap.c:4312
```

The line ccl_correlation.c:130 is where it frees some memory after an error.
I think it's not actually a double free, but a memory overspill inside the interpolator function.

At a higher level of course, if the C_ell are all zero you can immediately skip to returning zero for a correlation function.

**Comment by c-d-leonard** [comment]
Thanks for finding this! It looks like it might be related / the same as Issue #785. I will have a look; @damonge may also have thoughts?

**Comment by damonge** [comment]
Yes, I suspect it has to do with how we chose to extrapolate the C_ells logarithmically. Log(0) is not great.

I meant to look into this but haven't had a chance yet.

**Comment by c-d-leonard** [comment]
@joezuntz is this fully solved by your recently merged PR?

**Comment by joezuntz** [comment]
It is for me - I wouldn't want to claim that the same issue will never raise its head in other situations, but it's fine for me for now.  Maybe close this but re-open later if needed?

**Comment by c-d-leonard** [comment]
Sounds good.
