### ISSUE TITLE
Installing CCL on Ubuntu WSL 2

### ISSUE THREAD

**Issue by LisaGoh** [LSSTDESC/CCL#827]
Hi! I need to install CCL for a research project at school. However my computer is running on a Windows OS. I've tried installing it through the Windows subsystem for Linux (I am using Ubuntu) but I am getting an error.

My command is 'pip3 install pyccl'

The error message is:
Traceback (most recent call last):
  File "/usr/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 57, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1342, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1314, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1443, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1483, in _fill_cache
OSError: [Errno 5] Input/output error: '/usr/lib/python3/dist-packages/pkg_resources'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1342, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1314, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1443, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1483, in _fill_cache
OSError: [Errno 5] Input/output error: '/usr/lib/python3/dist-packages/apport'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 57, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1342, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1314, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1443, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1483, in _fill_cache
OSError: [Errno 5] Input/output error: '/usr/lib/python3/dist-packages/pkg_resources'

Is this an error with the installation or I am just not able to install it with a Windows OS? I'm very new to this and I'm sorry if I'm asking a silly question, but any help would be greatly appreciated!

**Comment by elisachisari** [comment]
I'm afraid we don't support installation on Windows. See https://github.com/LSSTDESC/CCL/issues/699.

**Comment by heather999** [comment]
Hi @LisaGoh  another option would be to use a docker image on your windows machine. We do have some docker images with python plus a variety of DESC packages like CCL availabile.  If you have docker available on your machine already, you could do: docker pull lsstdesc/desc-python:bleed and that would install an image containing the latest releases of packages like CCL.  You can install docker on windows if needed (I haven't done that on windows in a bit.. but I think this is a useful link):
