### ISSUE TITLE
setuptools_scm requires python3.7+

### ISSUE THREAD

**Issue by carlosggarcia** [LSSTDESC/CCL#949]
I have found that GitHub actions fail (in a different repo) when you do the tests with python3.6 and you try to install pyccl (both with `pip install pyccl` or `pip install git+https://github.com/LSSTDESC/CCL`). The error comes from `setuptools_scm` requiring python3.7+ (https://pypi.org/project/setuptools-scm/). I haven't been able to reproduce this in my laptop with a fresh conda environment, though.

```
Collecting git+https://github.com/LSSTDESC/CCL
  Cloning https://github.com/LSSTDESC/CCL to /tmp/pip-req-build-qwscu05t
  Running command git clone --filter=blob:none -q https://github.com/LSSTDESC/CCL /tmp/pip-req-build-qwscu05t
  Resolved https://github.com/LSSTDESC/CCL to commit d5408a777ab5fc4b2ae6fada2114a168b9bacee4
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/hostedtoolcache/Python/3.6.15/x64/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-qwscu05t/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-qwscu05t/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7eabotjw
       cwd: /tmp/pip-req-build-qwscu05t/
  Complete output (24 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-qwscu05t/setup.py", line 108, in <module>
      'Topic :: Scientific/Engineering :: Physics'
    File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/tmp/pip-req-build-qwscu05t/setup.py", line 49, in __init__
      super().__init__(attr)
    File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/setuptools/dist.py", line 442, in __init__
      k: v for k, v in attrs.items()
    File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/distutils/dist.py", line 281, in __init__
      self.finalize_options()
    File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/setuptools/dist.py", line 601, in finalize_options
      ep.load()(self, ep.name, value)
    File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
      return self.resolve()
    File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/tmp/pip-req-build-qwscu05t/.eggs/setuptools_scm-7.0.3-py3.6.egg/setuptools_scm/__init__.py", line 5
      from __future__ import annotations
      ^
  SyntaxError: future feature annotations is not defined
```

**Comment by rmjarvis** [comment]
Python 3.6 is officially pas end of life.  I'd recommend just dropping it as a supported platform rather than try to fix.  cf. https://endoflife.date/python

**Comment by nikfilippas** [comment]
@carlosggarcia closing this because py36 isn't updated anymore. You are getting this error because the `__future__` module doesn't have annotations, which were only added in Python 3.7.0b1.

**Comment by carlosggarcia** [comment]
@nikfilippas that's correct, but then you should require python3.7+ for pyccl. (see https://github.com/LSSTDESC/CCL/blob/aad5346a0ad3806fff8b1a19d304439ac3f2cdfb/setup.py#L106-L107)

**Comment by nikfilippas** [comment]
I think it's fair to say that since CCL is under active development, users shouldn't expect Python versions that are past their end of lives to be supported. But I agree, we have to update `setup.py`.
